
# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/plaid/go-envvar
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Run the tests
          command: go test ./...
